### ISSUE TITLE
Custom names patch doesn't boot

### ISSUE THREAD

**Issue by Kafmoon** [DeathChaos25/PQ2_MC_Name_Patch#5]
Whenever I try opening PQ2 after using the custom names patch, it just crashes instantly. I've tried with the canon names patch and that worked just fine, so I'm not sure what I'm doing wrong here. I put my crash dump in the attached .zip file.
[crash_dump_00000001.zip](https://github.com/DeathChaos25/PQ2_MC_Name_Patch/files/3502708/crash_dump_00000001.zip)

**Comment by DeathChaos25** [comment]
Sounds like you're deleting leftover characters from the name instead of filling the leftovers with 00s, if you change the size/address of course it's going to crash because it's not going to find what it's looking for.

**Comment by Kafmoon** [comment]
That makes sense, but what do I do if the name I'm inputting is longer than the name in code.bin?

**Comment by DeathChaos25** [comment]
Then you'll have to compile the patch from source yourself using Magikoopa to add longer names.

**Comment by AnAustinAn** [comment]
I have a similar problem, but with both the custom and canon name files. before the Nintendo 3ds logo even pops up I get an arm11 exception error.
